CREATE TABLE IF NOT EXISTS kb_articles (id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT NOT NULL, category TEXT NOT NULL, title TEXT NOT NULL, summary TEXT, body TEXT NOT NULL, tags TEXT, link_url TEXT, author_name TEXT NOT NULL, author_batch TEXT, author_key TEXT NOT NULL, by_admin INTEGER DEFAULT 0, status TEXT NOT NULL DEFAULT 'pending', featured INTEGER DEFAULT 0, review_note TEXT, reviewed_by TEXT, reviewed_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, ip TEXT, credits TEXT);
CREATE TABLE IF NOT EXISTS kb_stats (article_ref TEXT PRIMARY KEY, views INTEGER NOT NULL DEFAULT 0, helpful INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS kb_comments (id INTEGER PRIMARY KEY AUTOINCREMENT, article_ref TEXT NOT NULL, body TEXT NOT NULL, author_name TEXT NOT NULL, author_batch TEXT, author_key TEXT NOT NULL, by_admin INTEGER DEFAULT 0, status TEXT NOT NULL DEFAULT 'pending', review_note TEXT, reviewed_by TEXT, reviewed_at TEXT, created_at TEXT NOT NULL, ip TEXT);
INSERT INTO kb_articles (type, category, title, summary, body, tags, link_url, author_name, author_batch, author_key, status, featured, reviewed_by, reviewed_at, created_at, updated_at) VALUES
('How-to guide','Liens & Subrogation','Requesting a Medicare conditional payment letter','Where to request it, what to include, and how long it takes.','1. Log in to the MSPRP portal.\n2. Upload the proof of representation.\n3. Request the conditional payment letter.\n\n**Tip:** it usually takes 65 days.','medicare,lien','https://www.cob.cms.hhs.gov/MSPRP/','Ana Reyes','Batch 9','ana reyes|batch 9','published',1,'trainer1','2026-08-01T00:00:00Z','2026-07-30T00:00:00Z','2026-08-01T00:00:00Z'),
('Tip','Intake & Client Communication','Confirm the client''s preferred language first','Saves a second call.','Ask which language they prefer before starting the intake questions, and note it in the file.','intake','', 'Jo Cruz','Batch 11','jo cruz|batch 11','published',0,'trainer1','2026-08-05T00:00:00Z','2026-08-04T00:00:00Z','2026-08-05T00:00:00Z'),
('Checklist','General','Draft still waiting','Pending one.','A pending post body that is long enough.','', '', 'Jo Cruz','Batch 11','jo cruz|batch 11','pending',0,NULL,NULL,'2026-08-06T00:00:00Z','2026-08-06T00:00:00Z');
INSERT INTO kb_stats VALUES ('a:1', 42, 7);
INSERT INTO kb_comments (article_ref, body, author_name, author_batch, author_key, status, created_at) VALUES ('a:1','This worked for me, took 50 days.','Kim Lee','Batch 10','kim lee|batch 10','approved','2026-08-10T00:00:00Z');
